//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITA
    {
        public decimal ID_cita { get; set; }
        public decimal ID_mascota { get; set; }
        public System.DateTime Fecha_cita { get; set; }
        public string Observaciones { get; set; }
        public decimal ID_tipo_cita { get; set; }
    
        public virtual MASCOTA MASCOTA { get; set; }
        public virtual TIPO_CITA TIPO_CITA { get; set; }
    }
}
