//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        public decimal ID_orden { get; set; }
        public System.DateTime Fecha_orden { get; set; }
        public decimal ID_usuario { get; set; }
        public decimal ID_producto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Total { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
